### ISSUE TITLE
Error: image logstash/logstash/5.0.0-beta1:latest not found.

### ISSUE THREAD

**Issue by agonzalezm** [elastic/logstash-docker#1]
I am trying to pull image but not found.

[root@docker02 docker]# export ELASTIC_REG=docker.elastic.co/logstash
[root@docker02 docker]# export LOGSTASH_VERSION=5.0.0-beta1
[root@docker02 docker]# export LOGSTASH_IMAGE=$ELASTIC_REG/logstash/$LOGSTASH_VERSION

[root@docker02 docker]# docker run -it -v /my/logstash/configs/:/opt/logstash/conf.d/ $LOGSTASH_IMAGE
Unable to find image 'docker.elastic.co/logstash/logstash/5.0.0-beta1:latest' locally
Pulling repository docker.elastic.co/logstash/logstash/5.0.0-beta1
docker: Error: image logstash/logstash/5.0.0-beta1:latest not found.
See 'docker run --help'.

[root@docker02 docker]# docker pull $LOGSTASH_IMAGE
Using default tag: latest
Pulling repository docker.elastic.co/logstash/logstash/5.0.0-beta1
Error: image logstash/logstash/5.0.0-beta1:latest not found

**Comment by jordansissel** [comment]
Maybe 5.0.0-beta1 isn't published as a docker image yet? I don't know if we even do betas/alphas for docker images. @jarpy?

**Comment by agonzalezm** [comment]
5.0.0-beta1 docker images for elasticsearch and kibana are published i was able to pull them from elastic docker repo. I guess logstash image is not published yet. Any estimation on when it will be published?

**Comment by jarpy** [comment]
Ah, thank you! You found a [typo in the documentation](https://github.com/elastic/logstash-docker/commit/9a7cdfa84cfdf04285ea05eac9b32a554271a11e). The short version is that the images are tagged by Logstash version, so `5.0.0-beta1` and `latest` are valid tags, but `5.0.0-beta1:latest` is not.

What this does not reveal is the development status of the image itself, which is currently "alpha", regardless of the release status of Logstash 5. I [updated the README](https://github.com/elastic/logstash-docker#description) to show that the image is currently experimental, and not production-ready.

**Comment by agonzalezm** [comment]
It is ok if it is alpha i am just using them for dev enviroment to test v5.0 and would like to pull them. But I still cant pull the image with the changes, i have tried these commands and none of them can find the image. Any idea?

docker pull docker.elastic.co/logstash/logstash
docker pull docker.elastic.co/logstash/logstash:5.0.0-beta1
docker pull docker.elastic.co/logstash/logstash:latest

**Comment by jarpy** [comment]
Sorry @agonzalezm. I hadn't pushed the current images to the public repository. They are now pushed and you should be able to pull them down.

Please let me know if you have bugs or suggestions. :beers:

**Comment by cvielma** [comment]
Hi @jarpy today I'm experiencing the same issue with 5.4.1 or latest. 5.4.0 works.

**Comment by jarpy** [comment]
Hi @cvielma,

Elastic Stack version 5.4.1 was only released about 8 hours ago. The images are available now.

With regard to the `latest` tag, we actually removed it some time ago. We ask that people specify a version, because we don't want their production systems to to start behaving oddly when we release, for example, version 6.0.0.
