### ISSUE TITLE
Request to install openssl to base centos system

### ISSUE THREAD

**Issue by KyleGalvin** [elastic/logstash-docker#108]
logstash-input-lumberjack (and likely other plugins) require an ssl key and certificate to operate.

I have tried the following to generate a self-signed cert:
RUN yum install openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /opt/ssl/snakeoilkey.pem -out /opt/ssl/snakeoilcert.pem

However, the base centos system does not have openssl installed, and the default user cannot access yum to add it, and I cannot escalate privileges with su (no password) or sudo (not installed).

It seems to me adding openssl to the docker image to the following script (line 21) could be considered within the scope of this project (as certificate generation is a necessary step for logstash in at least some configurations)

https://github.com/elastic/logstash-docker/blob/master/templates/Dockerfile.j2

If you do not agree that this is in the scope of your project, perhaps you have advice on an alternative way I can generate a (non-expired) self-signed cert when spinning up an instance of this image.

Cheers,
Kyle

**Comment by jarpy** [comment]
I would ask whether that `openssl` command really needs to run inside a Logstash container. The container model encourages us to think in terms of containers doing one job well. Certificate generation is a job, and I'd argue that it should be handled by a dedicated certificate generation container (or other process) that would create certs that would then be made available to the Logstash container.

Doing certificate generation inside the Logstash container effectively limits you to self-signed certificates, right? They don't really do anything for you. The certificates should, ideally, be coming from a real Public Key Infrastructure somewhere and getting added into Logstash, either at runtime or baked into a custom image. Maybe [Let's Encrypt](https://letsencrypt.org/) would be a good option for your site?

**Comment by KyleGalvin** [comment]
I agree that adding openssl in its entirety just to create a self-signed cert for a plugin is quite a bit of overhead.

Adding another container entirely dedicated to generating the same cert is likewise a lot of overhead.

From your message:
"The container model encourages us to think in terms of containers doing one job well"

I could argue that a container should be able to start its own plugins without outside help to qualify as doing 'one job well'.

I've managed a workaround for my issue by injecting a key from the host container into the logstash image. This works well enough.

If you feel openssl is out of scope, you can close this ticket. While it assists logstash functionality it is not a hard requirement, and thus falls into a grey area where someone needs to make a judgement call.

Cheers

**Comment by jarpy** [comment]
> I could argue that a container should be able to start its own plugins without outside help to qualify as doing 'one job well'.

Agreed. It's not ideal.

What I'd really like to see is the plugin allowing cleartext. Real SSL can be a pain to set up and driving people towards self-signed certs will just give some folks a false sense of security.

I really appreciate your thoughtful and reasonable discussion on this topic. In general, we (Elastic) have been very reticent on "package creep" in all our images. Thus, I am going to close this ticket, as you've kindly offered. Thanks again for being cool about it.

**Comment by jethr0null** [comment]
Thank you both. @KyleGavin, please do continue to file these types of issues in the future. We really appreciate the feedback.
