### ISSUE TITLE
Docker image doesn't expose ports in custom image

### ISSUE THREAD

**Issue by Rafael-Simonelli** [elastic/logstash-docker#111]
I'm working with a custom image and I want to expose some of container's ports. But when I run my image in Rancher and execute "nmap <my-service>" from another service in the same host, it reaches the service but no ports are avaible. Other services are normal, with their ports exposed just like defined in Dockerfile. Logstash also runs normally.

I've added the line above to the service in docker compose, but to no effect:

    ports:
    - 5000:5000/tcp

Here's my Dockerfile and my logstash.yml. What am I doing wrong, please?

	# Dockerfile
	FROM docker.elastic.co/logstash/logstash:6.4.2

	RUN rm -f /usr/share/logstash/pipeline/logstash.conf
	COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf

	RUN rm -f /usr/share/logstash/config/logstash.yml
	COPY logstash.yml /usr/share/logstash/config/logstash.yml

	EXPOSE 5000	
	
	# logstash.yml
	http.host: "127.0.0.1"
	http.port: 9600

**Comment by xeraa** [comment]
IMO this should go to https://discuss.elastic.co, since there is a good chance this is a Logstash configuration issue.

And without seeing the logstash.conf it's hard to guess if you are even exposing something on port 5000. Also some logs would be helpful.

**Comment by jarpy** [comment]
Yes.

Please come over to the [Logstash forum](https://discuss.elastic.co/c/logstash) with your `logstash.conf` and I'll do my best to help you there.

**Comment by Rafael-Simonelli** [comment]
OK, moved to Logstash forum. Thanks!

**Comment by Rafael-Simonelli** [comment]
For the record, the topic is https://discuss.elastic.co/t/docker-image-doesnt-expose-ports-in-custom-image/156479
