### ISSUE TITLE
how to install amazon_es plugin install

### ISSUE THREAD

**Issue by dev-chulbuji** [elastic/logstash-docker#130]
i cannot connect with aws elasticsearch.
can anyone help me?

or

```
elasticsearch {
        hosts => "{aws es endpoint}"
        index => "logstash-%{+YYYY.MM.dd}"
 }
```
this options connect to {aws es endpoint}:9200
can i remove 9200 default port ?

**Comment by robbavey** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
