### ISSUE TITLE
Use deb package?

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash-docker#14]
Looks like the docker image is based on ubuntu 16.04. Any reason not to use the deb package we publish with Logstash releases?

**Comment by jarpy** [comment]
It could certainly be worth a try. It'll be interesting to see what happens with all the init system magic (thank you) it does in the Docker environment, where we don't have an init system to speak of :).

Deep down, I suspect this is a legacy artefact from the initial plan to ship an image based on Alpine Linux. I think you are probably right that we should be using a distro package now that we are using a supported distro.

**Comment by jarpy** [comment]
Closing this since we are now using CentOS as the base. More significantly, using the OS package mostly adds support for the init system, which is absent in the container context.
