### ISSUE TITLE
The jdbc_static filter plugin ignores the jdbc_user setting when connecting to a database

### ISSUE THREAD

**Issue by edmondkong** [elastic/logstash-docker#149]
When running the Logstash container and using the [jdbc_static](https://www.elastic.co/guide/en/logstash/current/plugins-filters-jdbc_static.html#plugins-filters-jdbc_static-local_lookups) filter plugin, it will always try to connect to a database with the user of the Logstash container, ignoring the [jdbc_user](https://www.elastic.co/guide/en/logstash/current/plugins-filters-jdbc_static.html#plugins-filters-jdbc_static-jdbc_user) setting.

This was tested with the following configuration:
`jdbc_user => "postgres"`

Snippet of Docker Compose output:
`logstash         | [2019-06-05T14:53:20,243][ERROR][logstash.javapipeline    ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::Filters::Jdbc::ConnectionJdbcException: Java::OrgPostgresqlUtil::PSQLException: FATAL: role "logstash" does not exist>, :backtrace=>
`

To confirm the issue, I set the container to run as "root" user. 
Snippet of Docker Compose output:
`logstash         | [2019-06-05T14:51:35,545][ERROR][logstash.javapipeline    ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::Filters::Jdbc::ConnectionJdbcException: Java::OrgPostgresqlUtil::PSQLException: FATAL: role "root" does not exist>, :backtrace=>`

**Comment by robbavey** [comment]
This issue has been transferred to the [jdbc static filter plugin repo](https://github.com/logstash-plugins/logstash-filter-jdbc_static/issues/49)
