### ISSUE TITLE
logstash-output-monasca_log_api plugin install fails

### ISSUE THREAD

**Issue by michelechersich** [elastic/logstash-docker#17]
Hello,
I'm having problems in building a Docker container with Logstash 5.x and the logstash-output-monasca_log_api plugin version 0.5.3, that can be found here: https://rubygems.org/gems/logstash-output-monasca_log_api

The plugin installation fails as shown below:

`Building monasca-log-agent
Step 1/4 : FROM logstash:5
---> 413f93f5f1f2
Step 2/4 : RUN logstash-plugin install logstash-output-monasca_log_api
---> Running in 21f002491274
Validating logstash-output-monasca_log_api
Installing logstash-output-monasca_log_api
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-codec-json":
In snapshot (Gemfile.lock):
logstash-codec-json (= 3.0.2)

In Gemfile:
logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java

logstash-output-monasca_log_api (>= 0) java depends on
  logstash-codec-json (~> 0.1.6) java

logstash-output-udp (>= 0) java depends on
  logstash-codec-json (>= 0) java
Running bundle update will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

The problem seems to be that Logstash 5.x locks the logstash-codec-json plugin version to 3.0.2, whereas the logstash-output-monasca_log_api plugin depends on a previous version.

So far, I have not been able to do the suggested `bundle update`.
The bundle executable is there but when I try to execute it from inside the container, I just get:

`sh: 18: bundle: not found`

The bundle environment does not seem to be configured properly. Running the executable from Docker CLI or Dockerfile just fails:

`starting container process caused "no such file or directory"`

Any suggestion on how to deal with this problem?
Thanks

**Comment by jordansissel** [comment]
This is a problem that can be fixed by the author of the monasca_log_api
plugin updating it for logstash 5.x

The specific dependency issue is this:

ogstash-output-monasca_log_api (>= 0) java depends on
logstash-codec-json (~> 0.1.6) java

i recommend you follow up with the plugin author for this issue as it is
not specific to logstash docker

**Comment by jordansissel** [comment]
Closing since I believe this is not related to the logstash docker image.
