### ISSUE TITLE
path.config settings file entry is ignored

### ISSUE THREAD

**Issue by mpalmer** [elastic/logstash-docker#24]
I'm finding all the rippers today...

Somewhat the inverse of #23: this time, instead of the command line being ignored, the *settings file* is ignored.  My `logstash.yml` looks like this:

```
pipeline:
  workers: 64
  batch:
    size: 250
path:
  config: '/logstash/logstash.conf'
  queue: '/logstash/queue'
config:
  reload:
    automatic: true
```

I've confirmed that logstash is, indeed, reading this on startup by mangling a key name and noting that logstash fails to start.

However, the contents of `/logstash/logstash.conf` is not read -- the default "beats" input is started instead:

```
$ docker run -v /srv/docker/logstash:/logstash -e LS_SETTINGS_DIR=/logstash --rm docker.elastic.co/logstash/logstash:5.2.2
Could not find log4j2 configuration at path /logstash/log4j2.properties. Using default config which logs to console
21:30:30.355 [LogStash::Runner] INFO  logstash.agent - No persistent UUID file found. Generating new UUID {:uuid=>"62331978-ec56-4e93-a17b-c03728d5721f", :path=>"/usr/share/logstash/data/uuid"}
21:30:30.899 [[.monitoring-logstash]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://logstash_system:xxxxxx@localhost:9200/_xpack/monitoring/?system_id=logstash&system_api_version=2&interval=1s]}}
21:30:30.900 [[.monitoring-logstash]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash_system:xxxxxx@localhost:9200/, :path=>"/"}
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAuthCache).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
21:30:30.998 [[.monitoring-logstash]-pipeline-manager] WARN  logstash.outputs.elasticsearch - Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTP:0x72a718e4 URL:http://logstash_system:xxxxxx@localhost:9200/_xpack/monitoring/?system_id=logstash&system_api_version=2&interval=1s>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash_system:xxxxxx@localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
21:30:30.999 [[.monitoring-logstash]-pipeline-manager] INFO  logstash.outputs.elasticsearch - New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>[#<URI::HTTP:0x21d220e0 URL:http://localhost:9200>]}
21:30:30.999 [[.monitoring-logstash]-pipeline-manager] INFO  logstash.pipeline - Starting pipeline {"id"=>".monitoring-logstash", "pipeline.workers"=>1, "pipeline.batch.size"=>2, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>2}
21:30:31.001 [[.monitoring-logstash]-pipeline-manager] INFO  logstash.pipeline - Pipeline .monitoring-logstash started
21:30:31.007 [[main]-pipeline-manager] INFO  logstash.pipeline - Starting pipeline {"id"=>"main", "pipeline.workers"=>64, "pipeline.batch.size"=>250, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>16000}
21:30:31.007 [[main]-pipeline-manager] WARN  logstash.pipeline - CAUTION: Recommended inflight events max exceeded! Logstash will run with up to 16000 events in memory in your current configuration. If your message sizes are large this may cause instability with the default heap size. Please consider setting a non-standard heap size, changing the batch size (currently 250), or changing the number of pipeline workers (currently 64)
21:30:31.355 [[main]-pipeline-manager] INFO  logstash.inputs.beats - Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
```

The config file I want to use doesn't mention beats at all:

```
$ docker run -v /srv/docker/logstash:/logstash -e LS_SETTINGS_DIR=/logstash --rm docker.elastic.co/logstash/logstash:5.2.2 grep beats /logstash/logstash.conf
```

And logstash should be able to read it Just Fine:

```
$ docker run -v /srv/docker/logstash:/logstash -e LS_SETTINGS_DIR=/logstash --rm docker.elastic.co/logstash/logstash:5.2.2 head -n 4 /logstash/logstash.conf
input {
  lumberjack {
    port            => 5150
    type            => "logs"
```

Interestingly, when I start logstash in the above configuration and look at my process listings, I find this:

```
22212 ?        Ssl    2:05 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Xmx1g -Xms256m -Xss2048k -Djffi.boot.library.path=/usr/share/logstash/vendor/jruby/lib/jni -Xbootclasspath/a:/usr/share/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/usr/share/logstash/vendor/jruby -Djruby.lib=/usr/share/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main /usr/share/logstash/lib/bootstrap/environment.rb logstash/runner.rb -f /usr/share/logstash/pipeline/
```

Specifically, the last bit is interesting: it appears that something is chucking in a `-f /usr/share/logstash/pipeline/`, which (I assume) overrides the value for `path.config` that I've set in the settings file.  This is supported by the fact that if I explicitly specify `-f` on the container command line:

```
$ docker run -v /srv/docker/logstash:/logstash -e LS_SETTINGS_DIR=/logstash --rm docker.elastic.co/logstash/logstash:5.2.2 logstash -f /logstash/logstash.conf
```

The process listing then shows that `-f` is set correctly:

```
10385 ?        Ssl    1:26 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Xmx1g -Xms256m -Xss2048k -Djffi.boot.library.path=/usr/share/logstash/vendor/jruby/lib/jni -Xbootclasspath/a:/usr/share/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/usr/share/logstash/vendor/jruby -Djruby.lib=/usr/share/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main /usr/share/logstash/lib/bootstrap/environment.rb logstash/runner.rb -f /logstash/logstash.conf
12
```

And, further, that my config is now applied:

```
Could not find log4j2 configuration at path /logstash/log4j2.properties. Using default config which logs to console
[...]
21:21:20.051 [[main]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://logstash-elasticsearch:9200/]}}
21:21:20.052 [[main]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash-elasticsearch:9200/, :path=>"/"}
21:21:20.119 [[main]-pipeline-manager] WARN  logstash.outputs.elasticsearch - Restored connection to ES instance {:url=>#<URI::HTTP:0x6c30c698 URL:http://logstash-elasticsearch:9200/>}
[...]
21:21:21.066 [[main]-pipeline-manager] INFO  logstash.inputs.lumberjack - Starting lumberjack input listener {:address=>"0.0.0.0:5150"}
```

**Comment by jarpy** [comment]
You're absolutely right. The default `-f` flag comes from [the Dockerfile](https://github.com/elastic/logstash-docker/blob/5.2/build/logstash/Dockerfile#L42).

The idea is to have a standard location for pipeline configuration, so that people who are following along with [the documentation](https://www.elastic.co/guide/en/logstash/5.2/docker.html#_configuring_logstash_for_docker) can just mount their configuration there and have it run. Like this:

```
docker run --rm -it -v ~/pipeline/:/usr/share/logstash/pipeline/ docker.elastic.co/logstash/logstash:5.2.2
```

If you want to mount your configuration in a non-standard location, then you will need to override the default `CMD` from the Dockerfile to ensure that Logstash looks in the right place.

**Comment by mpalmer** [comment]
So... that's it, then?

**Comment by jarpy** [comment]
I don't understand :)

**Comment by jarpy** [comment]
In all seriousness, please help me understand if I've missed something in my answer. Very happy to help if I can.

**Comment by jarpy** [comment]
Maybe I missed saying that the CLI flags override options in `logstash.yml`, so if you want `path.config` to be honoured from `logstash.yml`, you'll want to override `CMD` to one without a `-f` flag.

This works, for example:

``` bash
echo 'path.config: /logstash' > /tmp/logstash.yml
docker run --rm -v /tmp/logstash.yml:/usr/share/logstash/config/logstash.yml docker.elastic.co/logstash/logstash:5.3.0 logstash
```
By using a bare `logstash` as the command, `-f` is suppressed and the setting from `logstash.yml` is honoured.

Hopefully I am adding value here. 😃

**Comment by mpalmer** [comment]
At present, following the documentation (using a settings file rather than command line options), using the docker image, and wanting to place the pipeline configuration in a non-standard location does not work.  This is not, as far as I can see, documented anywhere, nor are any of the available workarounds.

What I took from your response is that you're OK with this state of affairs, and have no intention of improving either the code or documentation to prevent anyone else from stumbling onto this little land mine in the future.  I was enquiring as to whether my interpretation was, indeed, correct, and I should close this issue.

**Comment by jarpy** [comment]
Let's not close this. There's always room for improvement. I just need a bit of time to fully understand the issue and think about some ways to handle it.

The current implementation and docs are optimised for a simple out-of-box experience, where the user plays along and mounts their configuration at `/usr/share/logstash/pipeline`. Now we know that for more advanced applications, like yours, that need a custom location, some of the assumptions in the design cause conflicts. We want to make this work well for everyone, so let's see what we can figure out.

So far, I haven't thought of a way that we can get a perfect result for both cases without a change upstream in Logstash. That's not necessarily a problem though (hi @jordansissel!). Ideally, it would be great if we didn't have to use something so high-precedence as `--path.config` as the default in the Docker image. I think we could make the behaviour of the image really nice if we had either:

- A true, internal default location in Logstash, so that `-f` becomes non-mandatory.
- A method that has lower precedence than both `logstash.yml` and `--path.config`. Maybe `$LS_CONFIG_PATH` in the [spirit of `$LS_SETTINGS_PATH`](https://github.com/elastic/logstash/blob/88eb425b00e1b41810ff924f3a0370ce51e919b2/logstash-core/lib/logstash/runner.rb#L425).

What do you think?

**Comment by mpalmer** [comment]
I was actually a bit surprised that there *wasn't* an env var for the config ("pipeline"?  not sure what the preferred nomenclature is for the future) location, so that would be my go-to preference.  It's also easy to override a single environment variable in a Docker configuration, whereas anything you put on the command line is all-or-nothing -- the moment you override the command, any and all "default" command line parameters that were set are lost and you need to recreate them yourself if you want to keep any other default behaviours.  The environment is far more selective.

**Comment by jarpy** [comment]
Completely agree.

(I also, personally, find "config" and "settings" to be too similar in my mind, and try to always say "pipeline configuration" to remind myself.)

**Comment by jordansissel** [comment]
@jarpy I propose we stop specifying `-f` in the Dockerfile and let users specify the `path.config` in the `logstash.yml`. Any reason to force using `-f` ?

**Comment by jarpy** [comment]
Nope! I think I only recently became aware of `path.config`. That works really well. Thanks, Jordan.

f3369698440fecdfa800f0b9d1a560c82f3c98ed

**Comment by jarpy** [comment]
As a bonus, `PATH_CONFIG` is now valid as an environment variable via [the `env2yaml` mapper](https://github.com/elastic/logstash-docker/blob/master/build/logstash/env2yaml/env2yaml.go).

**Comment by jordansissel** [comment]
Sweeeeeet. <3
