### ISSUE TITLE
How to set LS_HEAP_SIZE?

### ISSUE THREAD

**Issue by pvledoux** [elastic/logstash-docker#27]
In docker-compose.yml, I tried

    environment:
      - "LS_HEAP_SIZE=3g"

But I still have 1g in the status of Logstash:
```
{
  "version": "5.3.0",
  "http_address": "0.0.0.0:9600",
  "jvm": {
    "pid": 1,
    "version": "1.8.0_121",
    "vm_name": "OpenJDK 64-Bit Server VM",
    "vm_version": "1.8.0_121",
    "vm_vendor": "Oracle Corporation",
    "start_time_in_millis": 1493031633901,
    "mem": {
      "heap_init_in_bytes": 268435456,
      "heap_max_in_bytes": 1037959168,
      "non_heap_init_in_bytes": 2555904,
      "non_heap_max_in_bytes": 0
    },
    "gc_collectors": [
      "ParNew",
      "ConcurrentMarkSweep"
    ]
  }
}
```

**Comment by jarpy** [comment]
Looking at the [current implementation](https://github.com/elastic/logstash/blob/5.3/bin/logstash#L11), it seems that specific JVM options like `LS_HEAP_SIZE` have been dropped in favour of the generic `LS_JAVA_OPTS`, which allows passing arbitrary arguments to the JVM. As a result, this will work in `docker-compose.yml`:

``` yaml
  environment:
        - LS_JAVA_OPTS=-Xmx3g
```

```
$ curl -s localhost:9600/_node/jvm | jq .jvm.mem.heap_max_in_bytes
3186360320
```

**Comment by pvledoux** [comment]
It works, thanks!

**Comment by CpuID** [comment]
Note this does not work as of 5.6.4.

**Comment by cafuego** [comment]
Setting `LS_JAVA_OPTS` works fine in 5.6.5.
