### ISSUE TITLE
Add exposed ports in dockerfile

### ISSUE THREAD

**Issue by ket4yii** [elastic/logstash-docker#28]
It allows to use, for example, registrator with custom CNI networking, that registers exposed ports if you pass *-internal* flag.

**Comment by jarpy** [comment]
Good call.

Added the Monitoring API and Beats input ports in 77f6ca1f0c81d5580e0aff3305e75639f5914b08. This will be released very soon in version 5.3.2.

Logstash could, of course, be listening on _any_ port, but are there any other obvious ones we should add?

**Comment by ket4yii** [comment]
I think this ones should be enough because of

> Logstash could, of course, be listening on any port

and if it's not enough in some cases, you can use ```--expose``` when you run container.
