### ISSUE TITLE
Environment variables not set in logstash config

### ISSUE THREAD

**Issue by mrcnc** [elastic/logstash-docker#29]
According to [the docs](https://www.elastic.co/guide/en/logstash/current/environment-variables.html) I should be able to specify a configuration file that can use environment variables for the pipeline config.   But when I try to set environment variables and mount this config file, it doesn't appear to work. 

```
input { stdin { } }
output {
  elasticsearch {
    hosts => "${ES_HOSTS}"
    user => "${ES_USERNAME}"
    password => "${ES_PASSWORD}"
    index => "logs"
  }
  stdout { codec => rubydebug }
}
```

You can reproduce this by mounting the config file above with a command like this:

```
docker run --rm -it \
-v /path/to/my-logstash.conf:/usr/share/logstash/pipeline/logstash.conf \
-e ES_HOSTS=http://my.elastic.node:9200 \
-e ES_USERNAME=elastic \
-e ES_PASSWORD=mypwd \
 docker.elastic.co/logstash/logstash:5.3.1
```

I see the error `[2017-04-26T19:03:02,580][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"bad URI(is not URI?): ${ES_HOSTS}"}` so the config file is copied to the correct location but the environment variables aren't replaced.  

Am I missing something, or should this be working?

**Comment by untergeek** [comment]
Have you tried encapsulating the value in single-quotes?
```
-e ES_HOSTS='http://my.elastic.node:9200' \
```

**Comment by jordansissel** [comment]
This is likely this bug in Logstash:
https://github.com/elastic/logstash/issues/6696

**Comment by mrcnc** [comment]
@untergeek Still have the same issue regardless of the quotes

@jordansissel Thx for pointing out that bug....I was able to use `docker.elastic.co/logstash/logstash:5.1.1` and it's working as expected.

**Comment by koursoh** [comment]
@mrcnc  did you manage to solve it?
