### ISSUE TITLE
Cannot dynamically provide properties containing '_' with environment variable

### ISSUE THREAD

**Issue by vberetti** [elastic/logstash-docker#31]
Example :

> docker run -e pipeline.unsafe_shutdown=true

In env2yaml.go, this environment variable will be passed to _normalizeSetting_ to be transformed as _pipeline.unsafe.shutdown_ and then rejected by _isValidSetting_.

**Comment by vberetti** [comment]
Here is a PR with a test to reproduce the problem and a fix : https://github.com/elastic/logstash-docker/pull/32

**Comment by jarpy** [comment]
Thanks for the PR!

Fixed by e8eaa11, and a806a7c.
