### ISSUE TITLE
logstash not honouring PATH_CONFIG?!

### ISSUE THREAD

**Issue by lgarvey** [elastic/logstash-docker#35]
Seem to have a weird issue where logstash reports that there is no config in `/usr/share/logstash/pipeline` directory, even though `PATH_CONFIG` has been set to `/usr/share/logstash/pipeline/prod/`

Here's the output from running the docker container:

```
Setting from environment 'path.config: /usr/share/logstash/pipeline/prod/'
Setting from environment 'xpack.monitoring.elasticsearch.url: rara'
Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
No persistent UUID file found. Generating new UUID {:uuid=>"c4ed0f71-e0c3-4ec4-b7c7-d00961e7ab26", :path=>"/usr/share/logstash/data/uuid"}
[2017-05-24T16:27:27,756][ERROR][logstash.agent           ] failed to fetch pipeline configuration {:message=>"No config files found: /usr/share/logstash/pipeline/. Can you make sure this path is a logstash config file?"}
```

Here's a fragment of the docker file :

```
FROM docker.elastic.co/logstash/logstash:5.3.2

ENV PATH_CONFIG=/usr/share/logstash/pipeline/prod/
[...]
COPY pipeline/ /usr/share/logstash/pipeline
```

The pipeline/ directory in the docker build context has a prod folder, inside which there is a logstash.conf folder.

**Comment by jarpy** [comment]
Hello,

The [patch](https://github.com/elastic/logstash-docker/commit/303eafecbd84753d42000772aafa14c1d1eec1ff) that enables setting `path.config` in this way is not currently in the 5.3 branch, and thus not in the 5.3.x images. I can backport it and publish new images.

In the mean time, would it be possible for you to use version 5.4.0? That version will behave as you expect.

Thanks.

**Comment by jarpy** [comment]
Actually, t3easy points out that backporting this change could cause a failure for existing users of the 5.3 image. Please let me know if you are able to move forward with 5.4.

**Comment by lgarvey** [comment]
Hi Jarpy,

Happy to move on 5.4.0, but I've just tested it and see that whilst the javac error has disappeared, it's now not installing any local gem plugins. It just hangs.  

I'll create a new ticket for this.

L

**Comment by jarpy** [comment]
Sorry to hear that :(

Let's move the conversation back to #33.
