### ISSUE TITLE
env2yaml not processing file in --path.confg

### ISSUE THREAD

**Issue by willfarrell** [elastic/logstash-docker#38]
Would be nice if the docker-entrypoint or logstash would replace ENV. This was a feature in the now deprecated docker image.

Hack I'm doing on docker-entrypoint:
```shell
#!/bin/bash -e

# Map environment variables to entries in logstash.yml.
# Note that this will mutate logstash.yml in place if any such settings are found.
# This may be undesirable, especially if logstash.yml is bind-mounted from the
# host system.
#env2yaml /usr/share/logstash/config/logstash.yml

PATH_CONFIG=/opt/logstash/conf.d #TODO grab from args
while IFS='=' read -r name value ; do
    # replace ${name}, ${name|default}, ${name | default} => value
    find ${PATH_CONFIG} -type f -name "*.conf" -print0 | xargs -0 sed -i.bak -r 's~\$\{'${name}' ?(|\|[^\}]{1,})}~'${value}'~g'
done < <(env)
rm ${PATH_CONFIG}/*.bak
if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
  exec logstash "$@"
else
  exec "$@"
fi
```

**Comment by jarpy** [comment]
Hi,

Could you expand a little bit on the problem and proposed solution? I'm having trouble understanding what the goal is.

Thanks.

**Comment by willfarrell** [comment]
When using the docker container from `https://hub.docker.com/_/logstash/`, strings like `${ENV_ELASTICSEARCH_HOST:default_value}` in the config would be replaced with their corresponding ENV in the container or fall back to the default value. I'm find now that I'm migrating to this new docker image, that the ENV var is not being replaced like it used too. The more I reflect on this the more I think this issues belongs to the logstash repo, but the existence of env2yaml makes me question that.

**Comment by willfarrell** [comment]
Just found your comment https://github.com/elastic/logstash-docker/issues/24#issuecomment-297903833. I'll test out using `ENV.PATH_CONFIG` tomorrow.

**Comment by willfarrell** [comment]
Figured out what changed.

- key: ${ENV} -> 'value'
- key: ${ENV}/path -> None <- This use case is mentioned in the docs
- key: '${ENV}' -> ${ENV}'
- key: "${ENV}" -> ${ENV}' <- This used to work in older versions

I've reconfigured my ENV to work around this. Would be nice if "${ENV}" was supported again.
