### ISSUE TITLE
env2yaml prints passwords to stdout

### ISSUE THREAD

**Issue by praseodym** [elastic/logstash-docker#41]
The env2yaml binary that is used to translate environment variables to a YAML configuration file [prints every setting to stdout](https://github.com/elastic/logstash-docker/blob/68a0e6ebb14764b50c5f9049981f6ae1360ac32c/build/logstash/env2yaml/env2yaml.go#L151). This is great for debugging, but does include any passwords that may be set (`xpack.monitoring.elasticsearch.password`, `xpack.monitoring.elasticsearch.ssl.truststore.password`, `xpack.monitoring.elasticsearch.ssl.keystore.password`). Because it's not unusual for container stdout to be ingested into external systems, this could lead to sensitive information leakage.

**Comment by jarpy** [comment]
This a very astute and important observation. Thank you!

The problem is fixed in 376faabfc7. Since this is an important security fix, I also pushed an updated image for `docker.elastic.co/logstash/logstash:5.5.0` (ID: `a60a8b1a3adb`).
