### ISSUE TITLE
env2yaml does not handle 'xpack.monitoring.elasticsearch.url' array

### ISSUE THREAD

**Issue by praseodym** [elastic/logstash-docker#42]
[According to Logstash documentation](https://www.elastic.co/guide/en/x-pack/current/monitoring-logstash.html), `xpack.monitoring.elasticsearch.url` can be set to an array of multiple Elasticsearch nodes to be used for monitoring. env2yaml only tries to [handle stringified booleans and ints](https://github.com/elastic/logstash-docker/blob/68a0e6ebb14764b50c5f9049981f6ae1360ac32c/build/logstash/env2yaml/env2yaml.go#L53) as special types for YAML marshalling, which means that using an array will never work. In practice, Logstash will throw an error when trying to parse a (stringified) array of monitoring nodes.

**Comment by jarpy** [comment]
Thanks for this great report. You made me realise that I had really gone the wrong way with parsing in `env2yaml`. I had essentially implemented a subset of a YAML parser, when all the while I had a full YAML parser that I could reuse.

#44 fixes this, and greatly simplifies the implementation of `env2yaml`.

I also pushed a once-off image to our registry, in case you'd like to try this out before 5.5.1 is released:

`docker.elastic.co/logstash/logstash:5.5.0-issue42`

**Comment by praseodym** [comment]
Thank you! The `5.5.0-issue42` issue works great for me.

**Comment by praseodym** [comment]
Is `env2yaml` even needed now that https://github.com/elastic/logstash/pull/7072 is merged?

**Comment by jarpy** [comment]
No indeed. elastic/logstash#7072 is the future. It will just take some time to get there ;).
