### ISSUE TITLE
Logstash fails to start without x-pack

### ISSUE THREAD

**Issue by kvalev** [elastic/logstash-docker#45]
I have a simple docker image that uses the default one and uninstalls x-pack:
```
ARG VERSION
FROM docker.elastic.co/logstash/logstash:$VERSION

# https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-uninstalling
RUN logstash-plugin remove x-pack
```

Said image is being used in a docker-compose, but the container fails to start with the error message:
```
[FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.elasticsearch.url" hasn't been registered>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:64:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:83:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:83:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:135:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:244:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:209:in `run'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

The semi-official image from DockerHub seems to be working just fine.

**Comment by kvalev** [comment]
It seems that the error was caused by some leftover xpack properties in the `/usr/share/logstash/config/logstash.yml` configuration file. It can be worked around the issue by removing the 3 xpack configuration entries, but ideally this should be done automatically when removing the plugin.

For completeness sake here is the updated Dockerfile:
```
ARG VERSION
FROM docker.elastic.co/logstash/logstash:$VERSION

# https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-uninstalling
RUN logstash-plugin remove x-pack
RUN sed -i '/xpack/d' /usr/share/logstash/config/logstash.yml
```

**Comment by aldaris** [comment]
Shouldn't the plugin validate its own configuration instead of logstash? Just got bitten by this issue as well.

**Comment by mkoertgen** [comment]
Adding my 2 cents here:
Please note that x-pack-plugin may not be preinstalled in all logstash versions (build arg) so that the command (and thus building the Dockerfile) may fail.

I just tested with 5.0.0, which fails, and with 5.6.3, which succeeds.
