### ISSUE TITLE
Not able to find 5.6.0 image

### ISSUE THREAD

**Issue by AshishThakur** [elastic/logstash-docker#48]
Following error is reported in case I try to pull 5.6.0 image, whereas 6.0.0-beta2 works fine. Is this image not published?
```
docker run --rm -it -v ~/pipeline/:/usr/share/logstash/pipeline/ docker.elastic.co/logstash/logstash:5.6.0
Unable to find image 'docker.elastic.co/logstash/logstash:5.6.0' locally
docker: Error response from daemon: manifest for docker.elastic.co/logstash/logstash:5.6.0 not found.
See 'docker run --help'.
```

**Comment by jarpy** [comment]
Hi,

5.6.0 hasn't been released in any format yet. 5.5.2 is the latest release in the 5.x series.

https://www.elastic.co/downloads/logstash

**Comment by saadqc** [comment]
@jarpy : The info on elastic.co is misleading.

"The Docker image for Logstash 5.6.1 can be retrieved with the following command:

docker pull docker.elastic.co/logstash/logstash:5.6.1"

 https://www.elastic.co/guide/en/logstash/current/docker.html#_pulling_the_image

**Comment by jarpy** [comment]
The image was pushed 7 hours ago. I guess we had a bit of latency between the docs and the image being updated. You must have been (un)lucky to find that window. Sorry.
