### ISSUE TITLE
Config path is not aligned with logstash documentation

### ISSUE THREAD

**Issue by guenhter** [elastic/logstash-docker#5]
The documentation of logstash
https://www.elastic.co/guide/en/logstash/5.0/config-setting-files.html
says, that pipeline files are stored under
`/etc/logstash/conf.d`

This image has different paths. This should be aligned (don't know which one is correct)

**Comment by jarpy** [comment]
Hi @guenhter. This answer may sound pedantic, so please forgive me if it does!

Specifically, the documentation says: "_On deb and rpm, you place the pipeline configuration files in the /etc/logstash/conf.d directory_". The Docker image is not built from deb or rpm packages, but from the platform-agnostic tarball distribution, which makes no assertions about the location of the pipeline config. When using the tarball, it's up to the administrator to decide where the pipeline configuration goes.

In the tarball distribution, the location of settings files is defined as being within `$LOGSTASH_HOME`, which in this case is `/usr/share/logstash`. My plan was to place the pipeline config alongside, with a distinctive name that made its purpose obvious, hence `/usr/share/logstash/pipeline`.

If you're interested, here's the documentation that specifies the file locations for OS package and tarball distributions of Logstash:

https://www.elastic.co/guide/en/logstash/5.0/dir-layout.html

By those rules, we _could_ place the pipeline config at `/etc/logstash/conf.d`, (or anywhere else we like!), but the settings files would still not be in the same place as with packaged installs. If we then decided to move the settings files to `/etc/logstash`, to match the packaged versions, we would then be truly violating the documentation of the tarball distribution.

'Hope that all makes sense.

Happy 'stashing.

**Comment by jordansissel** [comment]
I think /etc is only used with rpm or deb packages. The tarball and zip
installs won't look there by default.

**Comment by guenhter** [comment]
Thanks for the explanation.
Makes perfectly sense.
