### ISSUE TITLE
logstash-plugin update fails on redis 4.0.0 dependency due to java version 2.2 requirement

### ISSUE THREAD

**Issue by ryanschwartz** [elastic/logstash-docker#50]
Full debug output attached, but the root of it is
`Gem::InstallError: redis requires Ruby version >= 2.2.2.`

This dependency is the result of `s.add_runtime_dependency(%q<redis>, [">= 0"])` in the `logstash-input-redis-3.1.3.gemspec` that's being used.

Results can be replicated with a minimal Dockerfile:
```
FROM docker.elastic.co/logstash/logstash:5.5.2
# uncomment these ENV lines for full debug output
#ENV JARS_DEBUG=true
#ENV JARS_VERBOSE=true
#ENV DEBUG=1
RUN logstash-plugin update
```
[docker.build.txt](https://github.com/elastic/logstash-docker/files/1285502/docker.build.txt)

**Comment by jarpy** [comment]
Thanks for the report.

I think it would be best to raise this issue in the [logstash-input-redis repository](https://github.com/logstash-plugins/logstash-input-redis), where the code is maintained. This issue will affect all users of the plugin, not just Docker users.

```
$ tar -zxf logstash-5.5.2.tar.gz
$ ./logstash-5.5.2/bin/logstash-plugin update logstash-input-redis
Updating logstash-input-redis
Error Bundler::InstallError, retrying 1/10
An error occurred while installing redis (4.0.0), and Bundler cannot continue.
Make sure that `gem install redis -v '4.0.0'` succeeds before bundling.
```

**Comment by ryanschwartz** [comment]
Thanks @jarpy - new PRs opened in the effected `logstash-*-redis` repos.

https://github.com/logstash-plugins/logstash-input-redis/pull/58
https://github.com/logstash-plugins/logstash-output-redis/pull/53
