### ISSUE TITLE
env2yaml config support for cloud.* settings

### ISSUE THREAD

**Issue by tylerjl** [elastic/logstash-docker#62]
[There's a useful feature in Logstash 6.x](https://www.elastic.co/guide/en/cloud/current/ec-cloud-id.html#ec-cloud-id-logstash) which permits users to pass a `cloud.id` and `cloud.auth` setting in their settings yaml to automatically negotiate a Cloud URL endpoint for outputting to Elasticsearch. I attempted to use this but it looks like the setting isn't whitelisted in the env2yaml config. Could we get it included to permit passing those settings in through the environment?

**Comment by jordansissel** [comment]
We'll probably keep adding settings to Logstash and end up in this never-ending chase where env2yaml has to catch up to all our products adding settings. Can we stop this cycle somehow?

**Comment by tbragin** [comment]
@tylerjl Thanks for noticing!

@jordansissel @tylerjl  Does it make sense in the short while tactically to add these settings to the whitelist? I'm not sure how to stop the cycle :)

**Comment by jarpy** [comment]
Absolutely. I'll add them. Stopping the horror is an ongoing discussion.
