### ISSUE TITLE
Customizing logstash image

### ISSUE THREAD

**Issue by idirouhab** [elastic/logstash-docker#67]
Hi! I'd like to ask if is there any way to customize the logstash itself because I'd like to install some tools, let say `rsyslog` or `nmap` (I know that doesn't have any relation with Logstash)

Thanks.

**Comment by xeraa** [comment]
The documentation on customizing your images should get you started: https://www.elastic.co/guide/en/logstash/current/_configuring_logstash_for_docker.html#_custom_images

And it sounds more like a general Docker question. If it's not an issue with the image itself, please ask your question on https://discuss.elastic.co.
