### ISSUE TITLE
entrypoint: logstash -e doesn't work anymore with 6.1.2

### ISSUE THREAD

**Issue by Hermain** [elastic/logstash-docker#74]
I use logstash docker from within a stack in which I have the following service definition:

```logstash:
    image: docker.elastic.co/logstash/logstash:6.1.2
    environment:
      config.support_escapes: "true"
    logging:
      driver: "json-file"
    networks:
      - logging
    ports:
      - "12201:12201"
    entrypoint: logstash -e 'input { ........
                        output { stdout{ } elasticsearch { hosts => ["http://elasticsearch:9200"] } }'
```

Unfortunately this causes: `ERROR: Settings 'path.config' (-f) and 'config.string' (-e) can't be used simultaneously.`

I don't understand why this happens as I don't specify -f at all in the entrypoint. How can I get this to work?

**Comment by Hermain** [comment]
https://stackoverflow.com/questions/47607076/specify-logstash-configuration-on-command-line-with-docker answers my question I needed to do: 
`docker run --rm -it docker.elastic.co/logstash/logstash-oss:6.0.0 \
  --path.settings= -e 'input { stdin { } } output { stdout { } }'`

**Comment by darkpixel** [comment]
Ugly hack in my docker-compose file:
```
version: '3.1'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.3
    command: sh -c 'rm -v /usr/share/logstash/config/logstash.yml; logstash -e "input { syslog { port => 51414 } } output { elasticsearch { hosts => [\"elasticsearch:9200\"] } }"'
    restart: unless-stopped
    networks:
      - elasticnet
    expose:
      - "51414/udp"
networks:
  elasticnet:
    external: true
```

**Comment by jordansissel** [comment]
Can you tell me about the reasons you use `-e` instead of putting your pipeline configs in a file?

For background, the `-e` flag was primarily intended as for testing or one-off examples. 

We can try to bring back the functionality you are using, but I want to understand better your specific use cases and situation to see if we can provide an alternative.

**Comment by darkpixel** [comment]
@jordansissel I have a docker swarm with 5 nodes and I'm using portainer as a front end.  I don't want to have to create docker configuration items, then create a stack and reference those configuration items.  It's "too many moving parts" if I have to do disaster recovery.

Currently I can create my 'proxy' network and then paste my docker-compose file in to portainer.  I'm back online.  If I used docker configs, I would have to create the 'proxy' network, create a bunch of properly-named config files, paste in the docker-compose file, ensure I have the proper config files mapped to the proper logstash instances, etc...too much work. ;)

**Comment by jordansissel** [comment]
If your output is Elasticsearch, this means you probably can use Logstash's central management feature which lets you store the configuration in Elasticsearch and may solve your concern (which I admit I don't fully understand[1])

As an alternative, you can also specify a url (http/https) for where to fetch your config. For example:

```
input {
  generator { count => 1 }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

I created a gist (https://gist.github.com/jordansissel/afca9c30542262837e1f342cfd65aec2) and we can point Logstash at the raw file contents:

```
% bin/logstash -f https://gist.githubusercontent.com/jordansissel/afca9c30542262837e1f342cfd65aec2/raw/671bc59e04b85cbe240b881bbb0ffb149bf0a971/gistfile1.txt
{
  "@version"   => "1",
  "sequence"   => 0,
  "@timestamp" => 2018-02-01T06:21:20.546Z,
  "message"    => "Hello world!",
  "host"       => "pork.semicomplete.com"
}
```

Additionally, as a general concern, it seems lots of people have different preferences about how to run Logstash in Docker, and many of these preferences are incompatible with the others. Can you build an image which layers your changes on top of this one? If not, why not?

[1] you say "too much work" but I look at the complexity of the machine you just described and I am not understanding yet why 'put it in a file' is significant amounts of work. This is not a judgement against you - I try to say that I don't understand yet how you are measuring "work"  ;)

**Comment by Hermain** [comment]
I can build an image and put the changes on top. But when I develop my filters/logstash config for my docker swarm this will mean that everytime I change something I need to create a new image and push it to the registry and then redeploy.

Also it makes things way more complicated if I have to keep the configuration of logstash somewhere in another repo and then remember which image correspons to which state of that repo.
When using the official elk docker registry its also extremely easy to update the version of elk (just change version number and check if everything still works). Having a separate image just introduces another step.

Another thing is that I like having as many services as possible on official repositories as my own repository can be a bottleneck (when I deploy an application to a swarm of 10 servers, 10 servers will simultaniously docker pull a bunch of large images)

**Comment by darkpixel** [comment]
Sorry @jordansissel, my last reply was a bit brief.

I'm of the opinion that a docker-compose file should describe the *entire* application stack.  But when it comes to 'docker config' files you literally have to load a config file in (i.e. ```cat myconfig | docker config create myconfig.yml -```) and then reference that in your docker-compose file--something like:
```
version: '3.3'
services:
  heartbeat:
    image: 'docker.elastic.co/beats/heartbeat:6.1.2'
    configs:
      - source: monitoring.1
        target: /usr/share/heartbeat/heartbeat.yml
configs:
  monitoring.1:
    external: true
```

Docker configs can't be edited, and they can't be removed if a service is using them.  But they are a decent way of directing docker to insert a file into a docker image.   Anyways, if I wanted to make a change (in this example heartbeat) to the config file, I would have to edit the config, create a new docker config (maybe 'monitoring.2'), then go in and update the above docker-compose file and change two places from monitoring.1 to monitoring.2 and submit it...then the services would restart and I could go in and delete monitoring.1.

Using -e from the command line when it's simply for translating between syslog and elasticsearch is so much easier.  If I need something more complex like grok, I will probably end up using a config file, building my own custom image, or using the -f method to pull from a URL as you mentioned above.

Although personally I think the most ideal situation would be for something like logspout to support an elasticsearch output (as opposed to logspout -> syslog -> logstash -> elasticsearch).

**Comment by jakelandis** [comment]
I just tested this against a build candidate for the upcoming `6.2.0` release, and it appears that `-e` will work again.  

We made a change w/r/t defaulting to multiple pipeline configuration that inadvertently appears to have fix this.  Since this an incidental fix, we are not explicitly testing or making any guarantees about this behavior. 

I will leave this issue open for further discussion and to allow others to test when `6.2.0` is released.

**Comment by dliappis** [comment]
I see a failure when running the logstash-docker#master test suite (as of today) that _seems_ to indicate `-e pipeline.batch.delay` wasn't parsed properly:

```
   def test_setting_pipeline_batch_delay_from_environment(logstash):
10:25:59         logstash.restart(args='-e pipeline.batch.delay=36')
10:25:59 >       assert logstash.get_node_info()['pipelines']['main']['batch_delay'] == 36
10:25:59 E       KeyError: 'batch_delay'
10:25:59 
10:25:59 tests/test_settings.py:17: KeyError
```

This is certainly odd, as I don't see any changes in the corresponding product master branches or this repo. I thought I'd add this here, in case this is common knowledge.

**Comment by jarpy** [comment]
Though the `KeyError` is on the `batch_delay` key, which is at the bottom of the tree, so there is some structure being returned. Interesting.

Can I ask how you are generating the failure result? The [CI runner](https://devops-ci.elastic.co/view/Docker/job/elastic+logstash-docker+master+snapshot/) seems happy.

**Comment by dliappis** [comment]
Both good points. The automated CI seems to be happy again, so I consider this a transient issue related to a delayed start of the monitoring API.
