### ISSUE TITLE
Unable to configure SSL for beats input

### ISSUE THREAD

**Issue by cylon** [elastic/logstash-docker#77]
I have tried numerous versions of the logstash docker container and have not been able to successfully configure the beats input to use SSL.

Docker:  17.12.0-ce-win47
Logstash container: 6.2.1

Logs:
```
 logstash_1       | [2018-02-20T18:27:08,421][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
 logstash_1       | [2018-02-20T18:27:08,480][DEBUG][io.netty.handler.ssl.CipherSuiteConverter] Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 => ECDHE-ECDSA-AES256-GCM-SHA384
 logstash_1       | [2018-02-20T18:27:08,516][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"<LogStash::Inputs::Beats port=>5044, ssl=>true, ssl_certificate=>\"/etc/pki/tls/certs/logstash-forwarder.crt\", ssl_key=>\"/etc/pki/tls/private/logstash-forwarder.key\", id=>\"2ef1f57167a8005f6aca7168d8b8c4b409e6a55a2e96c3236597cadf72a5a9cc\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_2c167b7f-67b1-469a-a20d-baa39be9dd84\", enable_metric=>true, charset=>\"UTF-8\">, host=>\"0.0.0.0\", ssl_verify_mode=>\"none\", include_codec_tag=>true, ssl_handshake_timeout=>10000, tls_min_version=>1, tls_max_version=>1.2, cipher_suites=>[\"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384\", \"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\", \"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256\", \"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\", \"TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384\", \"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384\", \"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256\", \"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256\"], client_inactivity_timeout=>60, executor_threads=>8>", :error=>"Cipher `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` is not available", :thread=>"#<Thread:0x546f28e8 run>"}
 logstash_1       | [2018-02-20T18:27:08,531][DEBUG][logstash.inputs.tcp      ] Closing {:plugin=>"LogStash::Inputs::Tcp"}
```

Investigation showed that it seems to be caused by the inability to extract a shared library and load it from netty.  After extracting the library from the jar, I checked the following:

```
$ ldd /tmp/libnetty_tcnative_linux_x86_64.so
ldd: warning: you do not have execution permission for `/tmp/libnetty_tcnative_linux_x86_64.so'
        linux-vdso.so.1 =>  (0x00007fff110b5000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f7ec67ea000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f7ec65b3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7ec6397000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f7ec6193000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f7ec5dd0000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f7ec5bcd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7ec6dee000)
```

Other information: https://github.com/logstash-plugins/logstash-input-beats/issues/288

**Comment by jarpy** [comment]
Hi,

Sorry to say that I'm having trouble replicating this in my environment. There are a few references that suggest this could happen if your `/tmp` was mounted with the `noexec` option. Is it possible that this is happening in your container?

**Comment by cylon** [comment]
It certainly looks like it is  `noexec`, but it's not explicit.  The root `/` is an overlay.  From `mount`: `overlay on / type overlay (rw,relatime,lowerdir=...`, but no mention of noexec.

Here is my current docker compose config for logstash:
```
version: '3.3'
services:
    logstash:
      image: docker.elastic.co/logstash/logstash-oss:6.2.2
      ports:
        - "5044:5044"
      volumes:
        - D:\logstash_conf:/usr/share/logstash/pipeline/
        - D:\logstash_pki\private:/etc/pki/tls/private/
        - D:\logstash_pki\certs:/etc/pki/tls/certs/
```

Using a cert generated like: `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout logstash-forwarder.key -out logstash-forwarder.crt`

**Comment by jarpy** [comment]
Very curious! Thanks for the info.

What's your host OS, may I ask? Maybe I can bring up something similiar.

Have you tried bind-mounting something explicitly over `/tmp`? (Not as a fix, just as an experiment).

**Comment by jarpy** [comment]
Nevermind. I'm guessing Windows from the existing bind-mounts. :)

**Comment by jarpy** [comment]
Does this work in your container?

```
bash-4.2$ cp /bin/date /tmp
bash-4.2$ /tmp/date
Thu Feb 22 05:27:14 UTC 2018
```

**Comment by cylon** [comment]
Correct, it's Windows.  Copying and running date to /tmp worked.  I had thought about trying to bind /tmp, but forgot to try it.  I did this morning and still had the same issue.

So I start to re-create my environment from scratch and found out that it was an ordering issue.  I'm not sure why though.

For debugging I had my normal beats plugin `02-beats-input.conf`, notice the number, and had added a TCP input for some direct input `01-tcp-input.conf`, details below.  Without the TCP input, or with it *after* the beats input, everything loaded fine.

02-beats-input.conf:
```
input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
    ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
  }
}
```
01-tcp-input.conf:
```
input {
  tcp {
    'port' => 3333
  }
}
```
