### ISSUE TITLE
SSL issue with Logstash docker

### ISSUE THREAD

**Issue by mosheka** [elastic/logstash-docker#78]
These is an issue with SSL in JRuby 9.1.13.0 and it breaks the BigQuery output plugin. Please see the following issue: [(https://github.com/jruby/jruby/issues/4802)] and the stack trace below.
This issue should be solved by JRuby 9.1.14.0 as stated in the link

> [2018-03-08T14:39:28
> 386][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main"
>  :plugin=>"#<LogStash::OutputDelegator:0x71e006d5 @namespaced_metric=#<LogStash::Instrument::NamespacedMetric:0x704bf7ea @metric=#<LogStash::Instrument::Metric:0x2e1c48ce @collector=#<LogStash::Instrument::Collector:0x679a9dd0 @agent=nil
>  @metric_store=#<LogStash::Instrument::MetricStore:0x163df958 @store=#<Concurrent::Map:0x00000000000fac entries=3 default_proc=nil>
>  @structured_lookup_mutex=#<Mutex:0x4637ba6b>
>  @fast_lookup=#<Concurrent::Map:0x00000000000fb0 entries=55 default_proc=nil>>>>
>  @namespace_name=[:stats
>  :pipelines
>  :main
>  :plugins
>  :outputs
>  :\"06220cb17fd1ec99bacec88f4d0ff1f73395d878e416b02b0f4ceaf493116b95\"]>
>  @metric=#<LogStash::Instrument::NamespacedMetric:0x3315f3c1 @metric=#<LogStash::Instrument::Metric:0x2e1c48ce @collector=#<LogStash::Instrument::Collector:0x679a9dd0 @agent=nil
>  @metric_store=#<LogStash::Instrument::MetricStore:0x163df958 @store=#<Concurrent::Map:0x00000000000fac entries=3 default_proc=nil>
>  @structured_lookup_mutex=#<Mutex:0x4637ba6b>
>  @fast_lookup=#<Concurrent::Map:0x00000000000fb0 entries=55 default_proc=nil>>>>
>  @namespace_name=[:stats
>  :pipelines
>  :main
>  :plugins
>  :outputs]>
>  @out_counter=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: out value:0
>  @strategy=#<LogStash::OutputDelegatorStrategies::Single:0x3b61eeb0 @mutex=#<Mutex:0x4fcaaa0c>
>  @output=<LogStash::Outputs::GoogleBigQuery project_id=>\"31121231313\"
>  dataset=>\"test\"
>  csv_schema=>\"_id:STRING
> name:STRING
> location:STRING\"
>  key_path=>\"/usr/share/logstash/company.p12\"
>  service_account=>\"logstash@company-main.iam.gserviceaccount.com\"
>  temp_directory=>\"/tmp/logstash-bq\"
>  temp_file_prefix=>\"logstash_bq\"
>  date_pattern=>\"%Y-%m-%dT%H:00\"
>  flush_interval_secs=>2
>  uploader_interval_secs=>60
>  deleter_interval_secs=>60
>  id=>\"06220cb17fd1ec99bacec88f4d0ff1f73395d878e416b02b0f4ceaf493116b95\"
>  enable_metric=>true
>  codec=><LogStash::Codecs::Plain id=>\"plain_c9cd2a30-234e-4003-924e-7cf66c0b293f\"
>  enable_metric=>true
>  charset=>\"UTF-8\">
>  workers=>1
>  table_prefix=>\"logstash\"
>  table_separator=>\"_\"
>  ignore_unknown_values=>false
>  key_password=>\"notasecret\">>
>  @in_counter=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: in value:0
>  @id=\"06220cb17fd1ec99bacec88f4d0ff1f73395d878e416b02b0f4ceaf493116b95\"
>  @time_metric=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: duration_in_millis value:0
>  @metric_events=#<LogStash::Instrument::NamespacedMetric:0x53ddc3cf @metric=#<LogStash::Instrument::Metric:0x2e1c48ce @collector=#<LogStash::Instrument::Collector:0x679a9dd0 @agent=nil
>  @metric_store=#<LogStash::Instrument::MetricStore:0x163df958 @store=#<Concurrent::Map:0x00000000000fac entries=3 default_proc=nil>
>  @structured_lookup_mutex=#<Mutex:0x4637ba6b>
>  @fast_lookup=#<Concurrent::Map:0x00000000000fb0 entries=55 default_proc=nil>>>>
>  @namespace_name=[:stats
>  :pipelines
>  :main
>  :plugins
>  :outputs
>  :\"06220cb17fd1ec99bacec88f4d0ff1f73395d878e416b02b0f4ceaf493116b95\"
>  :events]>
>  @output_class=LogStash::Outputs::GoogleBigQuery>"
>  :error=>"certificate verify failed"
>  :thread=>"#<Thread:0x5035009e run>"}
> [2018-03-08T14:39:28
> 432][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main"
>  :exception=>#<Faraday::SSLError>
>  :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:228:in `connect_nonblock'"
>  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:938:in `connect'"
>  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:868:in `do_start'"
>  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857:in `start'"
>  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1409:in `request'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:967:in `fetch_access_token'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:1005:in `fetch_access_token!'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/google-api-client-0.8.7/lib/google/api_client/auth/jwt_asserter.rb:105:in `authorize'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-google_bigquery-3.2.3/lib/logstash/outputs/google_bigquery.rb:552:in `initialize_google_client'"
>  "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-google_bigquery-3.2.3/lib/logstash/outputs/google_bigquery.rb:209:in `register'"
>  "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:10:in `register'"
>  "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:42:in `register'"
>  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:341:in `register_plugin'"
>  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `block in register_plugins'"
>  "org/jruby/RubyArray.java:1734:in `each'"
>  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `register_plugins'"
>  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:735:in `maybe_setup_out_plugins'"
>  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:362:in `start_workers'"
>  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:289:in `run'"
>  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:249:in `block in start'"]
>  :thread=>"#<Thread:0x5035009e run>"}
> [2018-03-08T14:39:28
> 529][ERROR][logstash.agent           ] Failed to execute action {:id=>:main
>  :action_type=>LogStash::ConvergeResult::FailedAction
>  :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main
>  action_result: false"
>  :backtrace=>nil}

**Comment by jarpy** [comment]
Thanks for the report. Logstash itself bundles JRuby and we just ship whatever they provide.

It might be best to raise this issue against Logtash proper at: https://github.com/elastic/logstash.

Cheers.
