### ISSUE TITLE
logstash-input-google_pubsub by default

### ISSUE THREAD

**Issue by SebScoFr** [elastic/logstash-docker#82]
Logstash includes many plugin by default, unfortunately https://github.com/logstash-plugins/logstash-input-google_pubsub is not in the list and needs to be added manually.

This causes issues when running logstash on Kubernetes (I guess on Docker in general) which tries to start the pipeline when the plugin hasn't been installed yet, and therefore fails.

Would it be possible to include it by default in the image?

**Comment by jarpy** [comment]
Unfortunately, this is one of the "line drawing" questions. Which subset of optional plugins is the correct set to include in the base image?

I think you'd be best served by building your own image on top of this one with the plugin installed.
