### ISSUE TITLE
Please update UDP plugin on logstash 5.6.9

### ISSUE THREAD

**Issue by woqer** [elastic/logstash-docker#83]
The UDP plugin 3.3.1 is broken on logstash 5.6.9, it needs to be at least 3.3.2

I had to add into my Dockerfile a line with `logstash-plugin update logstash-input-udp`.

Is it possible to ship `docker.elastic.co/logstash/logstash:5.6.9` with the upgraded plugin?

Here the discussion in the elastic forum https://discuss.elastic.co/t/udp-input-is-crashing/128485

Thanks

**Comment by jarpy** [comment]
We don't really a mechanism for that in our build system. We will be shipping 5.6.10 soon, though.
