### ISSUE TITLE
logstash 5.6.8 from dockerhub does not catch console log

### ISSUE THREAD

**Issue by emretiryaki** [elastic/logstash-docker#84]
I have two machines (windows ,and linux) and the docker version 18.03.1-ce . Also these machines have different swarm cluster , not releated.

I run docker stack command with below compose file on both docker for window and docker on linux , but there is a problem that logstash does not capture any console logs comming from api on docker for linux. 

But  there is no  problem  on docker for windows. The console logs have captured and logstash sends to elastic.

----------------
![image](https://user-images.githubusercontent.com/11311254/40049563-c57ee40c-583d-11e8-9c6a-3cb05bd22eb5.png)

-----------
capture logs  docker swarm host in windows
![image](https://user-images.githubusercontent.com/11311254/40049667-0897db04-583e-11e8-8d76-6cddc64222d4.png)

capture logs docker swarm host in linux

![image](https://user-images.githubusercontent.com/11311254/40049730-2db62de6-583e-11e8-9895-5a4056a1a224.png)

**Comment by emretiryaki** [comment]
Hi, the problem i my fault. docker  in linux i I change url address  to  " gelf-address: udp://127.0.0.1:12201" and then the logstash stated to capture logs

**Comment by jarpy** [comment]
Thanks for reporting in agaikn @emretiryaki. Much appreciated.
