### ISSUE TITLE
[DEBUG]Error, cannot retrieve cgroups information 

### ISSUE THREAD

**Issue by mattblue84** [elastic/logstash-docker#89]
All,

Currently running docker elk in the following environment

- Description:    Ubuntu 18.04 LTS
- Release:        18.04
- Codename:       bionic

Docker version

 **Client:**
 **Version:      18.05.0-ce**
 **API version:  1.37**
 **Go version:   go1.9.5**
 ****Git commit:   f150324**
 **Built:        Wed May  9 22:16:25 2018**
 **OS/Arch:      linux/amd64**
 **Experimental: false**
 **Orchestrator: swarm****

**Server:**
 **Engine:**
  **Version:      18.05.0-ce**
  ****API version:  1.37 (minimum version 1.12)**
  **Go version:   go1.9.5**
  **Git commit:   f150324****
  **Built:        Wed May  9 22:14:32 2018**
  **OS/Arch:      linux/amd64**
  **Experimental: false**

Current Docker **logstash** version is 6.0.0

**Issue:**

Docker logstash produces the following debug messages

`"[2018-06-25T03:36:30,290][DEBUG][logstash.instrument.periodicpoller.cgroup] Error, cannot retrieve cgroups information {:exception=>"NoMethodError", :message=>"undefined method `[]' for nil:NilClass"}"`

`"[2018-06-25T03:36:30,578][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}"`

`"[2018-06-25T03:36:30,578][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}"`

I can confirm that the logstash container is receiving events but for some reason they are not being passed to Elasticsearch. I have other logstash containers that are send events successfully to the same Elasticsearch container

Any help or pointers would be appreciated

Regards

**Comment by jarpy** [comment]
I think this is probably an example of elastic/logstash#6824. Is there anything in that thread that seems appropriate to your environment?

**Comment by Wirone** [comment]
I, too, have plenty of `Error, cannot retrieve cgroups information {:exception=>"NoMethodError", :message=>"undefined method '[]' for nil:NilClass"}`. I've installed ELK as Docker stack recently and I'm facing issues with it - now I've changed logger level and I see I got this error every 3-5 seconds.

I'm using `docker.elastic.co/logstash/logstash-oss:6.3.0` image.

**Comment by jarpy** [comment]
Which distribution and kernel are you running, @Wirone? Did you find anything in elastic/logstash#6824 that seems relevant?

**Comment by Wirone** [comment]
@jarpy we're on Ubuntu 18.04, I can't check kernel right now. I did not look for it later because after initial problems with Kibana it started to work (but probably with this logs still appearing).

**Comment by prehor** [comment]
Similar errors with docker.elastic.co/logstash/logstash-oss:6.3.1 an Docker for macOS 18.03.1-ce-mac65:

```
[DEBUG][logstash.instrument.periodicpoller.cgroup] Error, cannot retrieve cgroups information {:exception=>"Errno::ENOENT", :message=>"No such file or directory - /sys/fs/cgroup/cpuacct/docker/9db615df8e86bc5c55c032fdf6575f1c3594d14af3877675464c3fddaa19d296/cpuacct.usage"}
```

Inside the container is missing the `/sys/fs/cgroup/cpuacct/docker` directory.

**Comment by edernucci** [comment]
Same here on Kubernetes on Azure:
```
Linux aks-nodepool1-27335126-0 4.15.0-1018-azure #18~16.04.1-Ubuntu SMP Thu Jul 19 13:13:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Logs:
```
[2018-08-07T20:29:15,549][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2018-08-07T20:29:15,549][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}
[2018-08-07T20:29:15,775][DEBUG][logstash.instrument.periodicpoller.cgroup] Error, cannot retrieve cgroups information {:exception=>"Errno::ENOENT", :message=>"No such file or directory - /sys/fs/cgroup/cpuacct/kubepods/burstable/pod5e60e22d-9a76-11e8-a729-ae2b44ea28fd/b8f3fb23e6efc459b83586b88ceb4455483e9f5d93dada257913213c1370a67e/cpuacct.usage"}
```
Logstash 6.3.2 (docker version)

**Comment by smalenfant** [comment]
Same problem in OpenShift and also under docker in Centos 7. Seems like the Elastic container reports just fine.

**Comment by ewgraf** [comment]
Same under docker in Windows 10

**Comment by jarpy** [comment]
It looks like elastic/logstash#6797 may be the solution that is needed here.

**Comment by guyboertje** [comment]
#jarpy et al

This issue is not related to [logstash 6824](https://github.com/elastic/logstash/issues/6824) or [logstash 6797](elastic/logstash#6797) as those deal with the case when the cgroup files/directories are not found in the places that we (naively) expect them to be. 

This is a different error. The files are found and read. The `logstash/instrument/periodicpoller/cgroup` Ruby file tries to parse the contents of these files. The error `undefined method[]' for nil:NilClass` probably means that some regex match, while parsing, didn't.

Either this means that the file is empty or the content structure is different to what has been coded for.

It is difficult to move forward on this. While #6797 may provide a solution i.e. providing the user with a means to override the built-in paths, we may still have a problem if the user overrides LS erroneously. Further, if the structure has changed (under what circumstances?) then we need to discover how we can detect and code for this.

**Comment by guyboertje** [comment]
@jarpy ^ Apologies.

**Comment by jarpy** [comment]
Thanks, @guyboertje. Is there a mitigation that you could suggest?

**Comment by guyboertje** [comment]
No clue yet. I'm trying to track the problem in https://github.com/elastic/logstash/issues/6824

**Comment by guyboertje** [comment]
The `undefined method[]' for nil:NilClass` fault has been identified. It occurs when there is an entry in the `/proc/self/cgroup` file that looks like this `0::/user.slice/user-1000.slice/session-932.scope`
We expect `<N>:<category>:<path>`.

**Comment by guyboertje** [comment]
The `No such file or directory` fault is caused when we parse the line from `/proc/self/cgroup` with the `cpu,cpuacct` category, take the path we find there and build a path that is supposed to be where the file `cpuacct.usage` (there are others) is, but the file is not in that location.

I have told, via the error message, many times where it is not but I have yet to find out where the alternative path to the file is and therefore how I would change the code to construct the correct path to it.

**Comment by guyboertje** [comment]
Is it possible that in some cases the symlinks are missing?

`/sys/fs/cgroup/cpu` -> `/sys/fs/cgroup/cpu,cpuacct
`/sys/fs/cgroup/cpuacct` -> `/sys/fs/cgroup/cpu,cpuacct

I know there are some cases (historic) where the directory is `cpuact,cpu` i.e. reversed.

Anyway, I'm going to implement the hack as done in ES and Kibana.

**Comment by tpaz** [comment]
I have the same issue, yet the symbolic links are there and in the right order.

**Comment by guyboertje** [comment]
@jarpy 

PR in logstash https://github.com/elastic/logstash/pull/9999 - looking release to LS 6.4.next and to backport to 5.6.next
I will create one for this to provide the override. Must coordinate releases.
