### ISSUE TITLE
Experimental Java Execution setting as an environment variable

### ISSUE THREAD

**Issue by danleerunk** [elastic/logstash-docker#99]
A number of settings are available to be configured via environment variables we can pass in, but according to [this list](https://github.com/elastic/logstash-docker/blob/c2f41a5763f9e5083130782413cc6650d3374abd/build/logstash/env2yaml/env2yaml.go#L50), `experimental-java-execution` isn't one of them.

That setting can be configured in a custom `logstash.yml` file which we can point the container to, but support for a `PIPELINE_JAVA_EXECUTION=true` environment variable would be preferred, and would bring it in-line with other settings.

Let me know if you have any questions!

**Comment by jarpy** [comment]
Am I right in thinking that `--experimental-java-execution` is a CLI flag and no equivalent exists in `logstash.yml`?

The current mechanism for supporting environment variables in the image is to map them to settings in `logstash.yml`. So to support this feature, I think we should either:

1. Make the setting valid in `logstash.yml`
2. Add a special case in the image that will detect an environment variable and add a CLI flag to the Docker `CMD`.

Personally, I prefer the first option, since it removes a special case in Logstash, rather than adding a special case in the image.

**Comment by jarpy** [comment]
Will [this](https://github.com/elastic/logstash/blob/c6cd247ec335a7010502091964f569497616b3de/logstash-core/lib/logstash/pipeline_settings.rb#L17) be honoured at the top level of `logstash.yml`? If so, then we just need to add it to env2yaml and I think we're done.

**Comment by original-brownbear** [comment]
@jarpy  Disclaimer: I'm not on the LS team any more and I think the answer to your question(s) has changed in my absence.

@jsvd and/or @danhermann should be able to help you here better :)

**Comment by jsvd** [comment]
> Can I set pipeline.java_execution in the top level of logstash.yml?

you can: 

```
# disabled (default)
% grep java config/logstash.yml
pipeline.java_execution: false
/tmp/logstash-6.5.0 % echo 1 | bin/logstash -e "" | grep java
/tmp/logstash-6.5.0 %    

# enabled
/tmp/logstash-6.5.0 % grep java config/logstash.yml
pipeline.java_execution: true
/tmp/logstash-6.5.0 % echo 1 | bin/logstash -e "" | grep java
[2018-11-13T09:49:39,461][INFO ][logstash.javapipeline    ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, :thread=>"#<Thread:0x7e6310ad run>"}
[2018-11-13T09:49:39,522][INFO ][logstash.javapipeline    ] Pipeline started {"pipeline.id"=>"main"}
[2018-11-13T09:49:40,776][INFO ][logstash.javapipeline    ] Pipeline terminated {"pipeline.id"=>"main"}
/tmp/logstash-6.5.0 %
```

> Is it possible to see, through the stats API, when Java execution is enabled?

We don't provide this through the stats API. Since the plan is to make java execution default for either 6.6 or another upcoming version, I don't think we will implement this.
